// User Constant
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ERROR = 'CLEAR_ERROR';

// Patients Constant
export const GET_PATIENTS = 'GET_PATIENTS';
export const PAITENT_ERROR = 'PAITENT_ERROR';
export const CREATE_PATIENT = 'CREATE_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';
export const GET_PATIENT_BY_ID = 'GET_PATIENT_BY_ID';
export const CLEAR_PATIENT = 'CLEAR_PATIENT';
export const UPDATE_PATIENT = 'UPDATE_PATIENT';
export const FILTERED_PATIENTS = 'FILTERED_PATIENTS';
export const CLEAR_FILTER_PATIENT = 'CLEAR_FILTER_PATIENT';

// Appointment Constant
export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const GET_APPOINTMENT_BY_ID = 'GET_APPOINTMENT_BY_ID';
export const APPOINTMENT_ERROR = 'APPOINTMENT_ERROR';
export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const DELETE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const CLEAR_APPOINTMENT = 'CLEAR_APPOINTMENT';
export const FILTERED_APPOINTEMNTS = 'FILTERED_APPOINTEMNTS';
export const CLEAR_FILTER_APPOINTEMNT = 'CLEAR_FILTER_APPOINTEMNT';

// Medicament Constant
export const GET_MEDICAMENTS = 'GET_MEDICAMENTS';
export const MEDICAMENT_ERROR = 'MEDICAMENT_ERROR';
export const CREATE_MEDICAMENT = 'CREATE_MEDICAMENT';
export const GET_MEDICAMENT_BY_ID = 'GET_MEDICAMENT_BY_ID';
export const UPDATE_MEDICAMENT = 'UPDATE_MEDICAMENT';
export const DELETE_MEDICAMENT = 'DELETE_MEDICAMENT';
export const CLEAR_MEDICAMENT = 'CLEAR_MEDICAMENT';
export const FILTERED_MEDICAMENTS = 'FILTERED_MEDICAMENTS';
export const CLEAR_FILTER_MEDICAMENTS = 'CLEAR_FILTER_MEDICAMENTS';

// Consultation Constant
export const GET_CONSULTATIONS = 'GET_CONSULTATIONS';
export const GET_CONSULTATION_BY_ID = 'GET_CONSULTATION_BY_ID';
export const CONSULTATION_ERROR = 'CONSULTATION_ERROR';
export const CREATE_CONSULTATION = 'CREATE_CONSULTATION';
export const DELETE_CONSULTATION = 'DELETE_CONSULTATION';
export const UPDATE_CONSULTATION = 'UPDATE_CONSULTATION';
export const CLEAR_CONSULTATION = 'CLEAR_CONSULTATION';
export const FILTERED_CONSULTATIONS = 'FILTERED_CONSULTATIONS';
export const CLEAR_FILTER_CONSULTATION = 'CLEAR_FILTER_CONSULTATION';

// Prescription Constant
export const PRESCRIPTION_ERROR = 'PRESCRIPTION_ERROR';
export const CREATE_PRESCRIPTION = 'CREATE_PRESCRIPTION';
export const CLEAR_PRESCRIPTION = 'CLEAR_PRESCRIPTION';

// Prescribed Medicament Constant
export const GET_PRESCRIBED_MEDICAMENTS = 'GET_PRESCRIBED_MEDICAMENTS';
export const CREATE_PRESCIBED_MEDICAMENT = 'CREATE_PRESCIBED_MEDICAMENT';
export const PRESCIRBED_MEDICAMENT_ERROR = 'PRESCIRBED_MEDICAMENT_ERROR';
export const DELETE_PRESCIRBED_MEDICAMENT = 'DELETE_PRESCIRBED_MEDICAMENT';
